import { memo } from "react";
import {
    ShoppingCart,
    ShoppingBag,
    Package,
    Box,
    Layers,
    Grid3X3,
    Tag,
    Barcode,
    Utensils,
    Apple,
    Beef,
    Coffee,
    Milk,
    Sandwich,
    Fish,
    Carrot,
    Salad,
    IceCream,
    Cookie,
    Wine,
    Beer,
    Droplets,
    Flame,
    Snowflake,
    Sparkles,
    Shirt,
    Baby,
    Dumbbell,
    Pill,
    Hospital,
    Home,
    Sofa,
    Lamp,
    Wrench,
    PenTool,
    BookOpen,
    Monitor,
    Smartphone,
    Headphones,
    Camera,
    Gamepad2,
    Car,
    Flower2,
    Leaf,
    Sun,
    Star,
    Banana,
    Cherry,
    Citrus,
    Grape,
    Egg,
    Pizza,
    Drumstick,
    Croissant,
    CakeSlice,
    Soup,
    Candy,
    Popcorn,
    CupSoda,
    SprayCan,
    ShowerHead,
    PackageOpen,
    Boxes,
    Cat,
    Dog,
    ToyBrick,
    Ham,
    Bean,
    BottleWine,
    ChefHat,
    Container,
    Fan,
    FishSymbol,
    GlassWater,
    Hammer,
    Hamburger,
    Heater,
    Keyboard,
    Microwave,
    Mouse,
    Plug,
    Printer,
    Recycle,
    Sprout,
    Tv,
    WashingMachine,
} from "lucide-react";
import { cn } from "@/lib/cn";

/** Shape: icon name (matches import key) → the Lucide icon component */
export const CATEGORY_ICONS: Record<string, React.ElementType> = {
    ShoppingCart,
    ShoppingBag,
    Package,
    Box,
    Layers,
    Grid3X3,
    Tag,
    Barcode,
    Utensils,
    Apple,
    Beef,
    Coffee,
    Milk,
    Sandwich,
    Fish,
    Carrot,
    Salad,
    IceCream,
    Cookie,
    Wine,
    Beer,
    Droplets,
    Flame,
    Snowflake,
    Sparkles,
    Shirt,
    Baby,
    Dumbbell,
    Pill,
    Hospital,
    Home,
    Sofa,
    Lamp,
    Wrench,
    PenTool,
    BookOpen,
    Monitor,
    Smartphone,
    Headphones,
    Camera,
    Gamepad2,
    Car,
    Flower2,
    Leaf,
    Sun,
    Star,
    Banana,
    Cherry,
    Citrus,
    Grape,
    Egg,
    Pizza,
    Drumstick,
    Croissant,
    CakeSlice,
    Soup,
    Candy,
    Popcorn,
    CupSoda,
    SprayCan,
    ShowerHead,
    PackageOpen,
    Boxes,
    Cat,
    Dog,
    ToyBrick,
    Ham,
    Bean,
    BottleWine,
    ChefHat,
    Container,
    Fan,
    FishSymbol,
    GlassWater,
    Hammer,
    Hamburger,
    Heater,
    Keyboard,
    Microwave,
    Mouse,
    Plug,
    Printer,
    Recycle,
    Sprout,
    Tv,
    WashingMachine,
};

interface IconPickerProps {
    value: string | null | undefined;
    onChange: (icon: string) => void;
}

export const IconPicker = memo(function IconPicker({ value, onChange }: IconPickerProps) {
    return (
        <div className="grid grid-cols-8 gap-1.5 max-h-48 overflow-y-auto p-1 rounded-lg border border-[var(--border-default)] bg-[var(--bg-subtle)]">
            {Object.entries(CATEGORY_ICONS).map(([name, Icon]) => (
                <button
                    key={name}
                    type="button"
                    title={name}
                    onClick={() => onChange(name)}
                    className={cn(
                        "flex items-center justify-center w-8 h-8 rounded-md transition-all duration-150 hover:scale-110",
                        value === name
                            ? "bg-[var(--color-oxygen-500)] text-white shadow-sm"
                            : "bg-[var(--bg-surface)] text-[var(--fg-muted)] hover:bg-[var(--color-oxygen-50)] hover:text-[var(--color-oxygen-600)]"
                    )}
                >
                    <Icon size={15} />
                </button>
            ))}
        </div>
    );
});
